ajisuke4_foodのみ/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users
  resource :user, expect: [:new, :create, :destroy]
  #　一覧画面を表示したいのでresourcesとする
  resources :foods do
    resource :favorites, only: [:create, :destroy]
  end
  resources :tastes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ajisuke4_foodのみ/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ajisuke4_foodのみ/app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
#    belongs_to :recipe
    belongs_to :food
    belongs_to :taste

    # recipe_idとuser_idの組みをuniqueつまり一通りにした　
    # 一人のユーザがあるレシピに対して複数回いいねするのはできない
 #   validates_uniqueness_of :recipe_id, scope:user_id
    # userがfood_id, taste_idの組みに対しいて一意
    validates_uniqueness_of :user_id, scope: [:food_id , :taste_id]

   
end

ajisuke4_foodのみ/app/models/food.rb
class Food < ApplicationRecord
    #belongs_to :taste
    has_many :favorites, dependent: :destroy
    has_many :tastes, through: :favorites

    def self.search(search) #ここでのself.はUser.を意味する
        if search
          Food.where(['food_name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
        else
          Food.all #全て表示。User.は省略
        end
    end
    
    with_options presence: true do
        validates :food_name
    end
end

ajisuke4_foodのみ/app/models/post.rb
class Post < ApplicationRecord
  def self.search(search)
    return Post.all unless search
    Post.where(['content LIKE ?', "%#{search}%"])
  end
end

ajisuke4_foodのみ/app/models/recipe.rb
class Recipe < ApplicationRecord
    # レシピは一人のuserによってかかれるので、user単数形
    belongs_to :user
    # １つのレシピに複数のいいねがつく + レシピが削除されたらいいねも削除
    has_many :favorites, dependent: :destroy

    with_options presence: true do
        validates :title
        validates :body
    end
     
end

ajisuke4_foodのみ/app/models/taste.rb
class Taste < ApplicationRecord
    # レシピは一人のuserによってかかれるので、user単数形
    #belongs_to :user
    # １つのレシピに複数のいいねがつく + レシピが削除されたらいいねも削除
    has_many :favorites, dependent: :destroy

    with_options presence: true do
        validates :title
        validates :body
    end
end

ajisuke4_foodのみ/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  # 一人のuserは複数のレシピを持てるのでrecipes複数形
  # dependent: :destroy userを削除するとそれに紐づくレシピも削除
  has_many :tastes, dependent: :destroy
  has_many :foods, dependent: :destroy
  # １つのレシピに複数のいいねがつく + レシピが削除されたらいいねも削除
  has_many :favorites, dependent: :destroy

  # そのユーザがあるレシピに対していいねを押したことがあったか？
  # views/recipes/index.html.erb でこの関数をしよう
  def already_favorited?(food)
    self.favorites.exists?(food_id: food.id)
  end
end

ajisuke4_foodのみ/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    #@foods = Food.all
    @foods = Food.search(params[:search])
    @tastes = Taste.all
  end

  

  def show
    @food = Food.find(params[:id])
    @tastes = @food.tastes
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to food_path(@food), notice: "投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
  end

  def search
    if params[:name].present?
      @food = Food.where('food_name LIKE ?', "%#{params[:name]}%")
    else
      @food = Food.none
    end
  end

  private 
  def food_params
    params.require(:food).permit(:food_name)
  end
end

ajisuke4_foodのみ/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

ajisuke4_foodのみ/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def search
        #Viewのformで取得したパラメータをモデルに渡す
        @posts = Post.search(params[:search])
      end
end

ajisuke4_foodのみ/app/controllers/tastes_controller.rb
class TastesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    # Tastesの全てのレコードを参照
    @tastes = Taste.all
  end

  def show
    @taste = Taste.find(params[:id])
#    @foods = 
  end

  def new
    @taste = Taste.new
  end

  def create
    @taste = Taste.new(taste_params)

    if @taste.save
      redirect_to taste_path(@taste), notice: "投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
  end

  private 
  def taste_params
    params.require(:taste).permit(:title, :body)
  end

end

ajisuke4_foodのみ/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before user登録 のactionを制限する(ただし、indexページは誰でも見れるように規制の対象外)
  before_action :authenticate_user!
  def show
  end

  def update
    @user = current_user
  end

  def edit
    @user = current_user
    # updateされたらリダイレクト
    if @user.update(user_params)
      redirect_to user_path, notice: "ユーザー情報を更新しました。"
    # されなかったらrender
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

ajisuke4_foodのみ/app/helpers/application_helper.rb
module ApplicationHelper
end

ajisuke4_foodのみ/app/helpers/favorites_helper.rb
module FavoritesHelper
end

ajisuke4_foodのみ/app/helpers/foods_helper.rb
module FoodsHelper
end

ajisuke4_foodのみ/app/helpers/home_helper.rb
module HomeHelper
end

ajisuke4_foodのみ/app/helpers/post_helper.rb
module PostHelper
end

ajisuke4_foodのみ/app/helpers/recipes_helper.rb
module RecipesHelper
end

ajisuke4_foodのみ/app/helpers/taste_helper.rb
module TasteHelper
end

ajisuke4_foodのみ/app/helpers/users_helper.rb
module UsersHelper
end

ajisuke4_foodのみ/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajisuke2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/3f27712743.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'あじすけ', root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
    

    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="Navber">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'マイページ', user_path, class: "nav-link" %>
        </li>
            <li class="nav-item">
                <%= link_to '味付けから探す', tastes_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to '食材から探す', foods_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% else %> 
      <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
            </li>
          </ul>
       </div>
      <% end %>
  </nav>

  <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
  <% end %>
  <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
  <% end %>

    <%= yield %>
  </body>
</html>