ajisuke4_foodのみ/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users
  resource :user, expect: [:new, :create, :destroy]
  #　一覧画面を表示したいのでresourcesとする
  resources :foods do
    resource :favorites, only: [:create, :destroy]
  end
  resources :tastes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ajisuke4_foodのみ/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ajisuke4_foodのみ/app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
#    belongs_to :recipe
    belongs_to :food
    belongs_to :taste

    # recipe_idとuser_idの組みをuniqueつまり一通りにした　
    # 一人のユーザがあるレシピに対して複数回いいねするのはできない
 #   validates_uniqueness_of :recipe_id, scope:user_id
    # userがfood_id, taste_idの組みに対しいて一意
    validates_uniqueness_of :user_id, scope: [:food_id , :taste_id]

   
end

ajisuke4_foodのみ/app/models/food.rb
class Food < ApplicationRecord
    #belongs_to :taste
    has_many :favorites, dependent: :destroy
    has_many :tastes, through: :favorites

    def self.search(search) #ここでのself.はUser.を意味する
        if search
          Food.where(['food_name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
        else
          Food.all #全て表示。User.は省略
        end
    end
    
    with_options presence: true do
        validates :food_name
    end
end

ajisuke4_foodのみ/app/models/post.rb
class Post < ApplicationRecord
  def self.search(search)
    return Post.all unless search
    Post.where(['content LIKE ?', "%#{search}%"])
  end
end

ajisuke4_foodのみ/app/models/recipe.rb
class Recipe < ApplicationRecord
    # レシピは一人のuserによってかかれるので、user単数形
    belongs_to :user
    # １つのレシピに複数のいいねがつく + レシピが削除されたらいいねも削除
    has_many :favorites, dependent: :destroy

    with_options presence: true do
        validates :title
        validates :body
    end
     
end

ajisuke4_foodのみ/app/models/taste.rb
class Taste < ApplicationRecord
    # レシピは一人のuserによってかかれるので、user単数形
    #belongs_to :user
    # １つのレシピに複数のいいねがつく + レシピが削除されたらいいねも削除
    has_many :favorites, dependent: :destroy

    with_options presence: true do
        validates :title
        validates :body
    end
end

ajisuke4_foodのみ/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  # 一人のuserは複数のレシピを持てるのでrecipes複数形
  # dependent: :destroy userを削除するとそれに紐づくレシピも削除
  has_many :tastes, dependent: :destroy
  has_many :foods, dependent: :destroy
  # １つのレシピに複数のいいねがつく + レシピが削除されたらいいねも削除
  has_many :favorites, dependent: :destroy

  # そのユーザがあるレシピに対していいねを押したことがあったか？
  # views/recipes/index.html.erb でこの関数をしよう
  def already_favorited?(food)
    self.favorites.exists?(food_id: food.id)
  end
end

ajisuke4_foodのみ/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def after_sign_in_path_for(resource)
        user_path
    end
    #def after_sign_up_path_for(resource)
    #    user_path
    #end
    def after_sign_out_path_for(resource_or_scope)
        new_user_session_path
    end

    def configure_permitted_parameters
        # 名前も新規登録できるようにした
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

ajisuke4_foodのみ/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    # def show
    #     @favorite = Favorite.find(params[:id])
    # end

    def create
        # current_user.favorites.create : current_userに結びついたいいねを取得 
        # →　あとは、どのレシピにいいねをしたか記録
        @favorite = current_user.favorites.create(food_id: params[:food_id], taste_id: params[:taste_id])
        # いいねしたあと前のページに戻る
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @food = Food.find(params[:food_id])
        @taste = Taste.find(params[:taste_id])
        # 下のrecipe_idには上でfind下recipe_idがはいる
        @favorite = current_user.favorites.find_by(food_id: @food.id, taste_id: @taste.id)
        @favorite.destroy
        # 万が一元いたurlがわからなかったらroot_pathへ
        redirect_back(fallback_location: root_path)
    end

end

ajisuke4_foodのみ/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    #@foods = Food.all
    @foods = Food.search(params[:search])
    @tastes = Taste.all
  end

  

  def show
    @food = Food.find(params[:id])
    @tastes = @food.tastes
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to food_path(@food), notice: "投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
  end

  def search
    if params[:name].present?
      @food = Food.where('food_name LIKE ?', "%#{params[:name]}%")
    else
      @food = Food.none
    end
  end

  private 
  def food_params
    params.require(:food).permit(:food_name)
  end
end

ajisuke4_foodのみ/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

ajisuke4_foodのみ/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def search
        #Viewのformで取得したパラメータをモデルに渡す
        @posts = Post.search(params[:search])
      end
end

ajisuke4_foodのみ/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before user登録 のactionを制限する(ただし、indexページは誰でも見れるように規制の対象外)
  before_action :authenticate_user!, except: [:index]
  def index
    # Recipesの全てのレコードを参照
    @recipes = Recipe.all
  end

  def show
    @recipe =  Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      redirect_to recipe_path(@recipe), notice: "投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
  end

  private 
  def recipe_params
    params.require(:recipe).permit(:title, :body)
  end
end

ajisuke4_foodのみ/app/controllers/tastes_controller.rb
class TastesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    # Tastesの全てのレコードを参照
    @tastes = Taste.all
  end

  def show
    @taste = Taste.find(params[:id])
#    @foods = 
  end

  def new
    @taste = Taste.new
  end

  def create
    @taste = Taste.new(taste_params)

    if @taste.save
      redirect_to taste_path(@taste), notice: "投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
  end

  private 
  def taste_params
    params.require(:taste).permit(:title, :body)
  end

end

ajisuke4_foodのみ/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before user登録 のactionを制限する(ただし、indexページは誰でも見れるように規制の対象外)
  before_action :authenticate_user!
  def show
  end

  def update
    @user = current_user
  end

  def edit
    @user = current_user
    # updateされたらリダイレクト
    if @user.update(user_params)
      redirect_to user_path, notice: "ユーザー情報を更新しました。"
    # されなかったらrender
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

ajisuke4_foodのみ/app/helpers/application_helper.rb
module ApplicationHelper
end

ajisuke4_foodのみ/app/helpers/favorites_helper.rb
module FavoritesHelper
end

ajisuke4_foodのみ/app/helpers/foods_helper.rb
module FoodsHelper
end

ajisuke4_foodのみ/app/helpers/home_helper.rb
module HomeHelper
end

ajisuke4_foodのみ/app/helpers/post_helper.rb
module PostHelper
end

ajisuke4_foodのみ/app/helpers/recipes_helper.rb
module RecipesHelper
end

ajisuke4_foodのみ/app/helpers/taste_helper.rb
module TasteHelper
end

ajisuke4_foodのみ/app/helpers/users_helper.rb
module UsersHelper
end

ajisuke4_foodのみ/app/views/favorites/index.html.erb
<h1>Favorite#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

ajisuke4_foodのみ/app/views/favorites/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
        </div>
        </div>
      </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/foods/edit.html.erb
<h1>Foods#edit</h1>
<p>Find me in app/views/foods/edit.html.erb</p>

ajisuke4_foodのみ/app/views/foods/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-10 mx-auto">
    <h3>食材から探す</h3>
    <%= form_tag foods_path, :method => 'get' do %> 
        <p>
           <%= text_field_tag :search, params[:search] %>
           <%= submit_tag "Search", :name => nil %>
         </p>
         <% end %>
    <div class="card"> 
    

      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">おすすめ食材</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td><%= link_to food.food_name, food_path(food)  %></td>
              <td></td>
            
                      </tr>
          <% end %>
        </tbody>
     </table>
     </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/foods/new.html.erb
<% if @food.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@food.errors.count, "error") %></h4>
    <p><%= pluralize(@food.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>新規投稿</h2>
      <%= form_for @food do |f| %>
        <div class="form-group">
          <label>レシピ名</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
      
        <div class="form-group">
          <label>作り方</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>
      
        <div>
          <%= f.submit class: "btn btn-success" %>
        </div>
    <% end %>  
    </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/foods/show.html.erb
<div class="row">
    <div class="col-10 mx-auto">
    　<h3><%= @food.food_name %>で人気の味付け</h3>
　　    <div class="card"> 
　　　　　　<table class="table table-hover">
        　<thead class="thead-dark">
          　<tr>
            　<th scope="col">おすすめ味つけ</th>
            　<th scope="col"></th>
          　</tr>
        　</thead>
        　<tbody>
        　<% @tastes.each do |taste| %>
            <tr>
              <td><%= link_to taste.title, taste_path(taste)  %></td>
              <td>
            <% if current_user.already_favorited?(@food) %>
            <%= link_to food_favorites_path(@food, taste_id:taste), method: :delete  do %>
              <i class="fas fa-heart"></i>
            <% end %>
            <% else %>
            <%= link_to food_favorites_path(@food, taste_id:taste), method: :post  do %>
                <i class="far fa-heart"></i>
              <% end %>  
            <% end %>
              <%= @food.favorites.count %>
          </td>
              <td></td>
            </tr>
            
            <% end %>
            <tr><td><%= link_to "みそ炒め", taste_path(2)  %></td><td></td></tr>
        </tbody>
     </table>
     </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

ajisuke4_foodのみ/app/views/recipes/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-10 mx-auto">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">レシピ名</th>
            <th scope="col">投稿者</th>
            <th scope="col">いいね</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
            <tr>
              <td><%= link_to recipe.title, recipe_path(recipe) %></td>
              <td><%= recipe.user.name %></td>
              <td>
                <% if current_user.already_favorited?(recipe) %>
                  <%= link_to recipe_favorites_path(recipe), method: :delete  do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                <%= link_to recipe_favorites_path(recipe), method: :post  do %>
                  <i class="fas fa-heart"></i>
                <% end %>
                <% end %>
                <%= recipe.favorites.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
     </table>
     </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/recipes/new.html.erb
<% if @recipe.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@recipe.errors.count, "error") %></h4>
    <p><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>新規投稿</h2>
      <%= form_for @recipe do |f| %>
        <div class="form-group">
          <label>レシピ名</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
      
        <div class="form-group">
          <label>作り方</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>
      
        <div>
          <%= f.submit class: "btn btn-success" %>
        </div>
    <% end %>  
    </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/recipes/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @recipe.title %></h5>
          <p class="card-text"><%= simple_format @recipe.body %></p>
          <p class="card-text">
            <small class="text-muted">更新日：<%= @recipe.updated_at.strftime("%Y-%m-%d") %></small>
          </p>

          <% if @recipe.user == current_user %>
            <%= link_to '編集', edit_recipe_path(@recipe), class: "btn btn-success" %>
            <%= link_to '削除', recipe_path(@recipe), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/tastes/edit.html.erb
<h1>Taste#edit</h1>
<p>Find me in app/views/taste/edit.html.erb</p>

ajisuke4_foodのみ/app/views/tastes/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-10 mx-auto">
    <h3>味付けから探す</h3>
    <table class="table table-hover">
        <thead class="thead-dark">
        
          <tr>
            <th scope="col">味付け</th>
          </tr>
        </thead>
        <tbody>
          <% @tastes.each do |taste| %>
            <tr>
              <td><%= link_to taste.title, taste_path(taste) %></td>
            </tr>
          <% end %>
        </tbody>
     </table>
     </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/tastes/new.html.erb
<h1>Taste#new</h1>
<p>Find me in app/views/taste/new.html.erb</p>

ajisuke4_foodのみ/app/views/tastes/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @taste.title %></h5>
          <p class="card-text"><%= simple_format @taste.body %></p>
          <p class="card-text">
            <small class="text-muted">更新日：<%= @taste.updated_at.strftime("%Y-%m-%d") %></small>
          </p>
        </div>
      </div>

      <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">おすすめ食材</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
     
        <tr><td>鶏肉 もも</td><td></td></tr>
        <tr> <td>ブリ</td><td></td></tr>  
        <tr><td>にんじん</td><td></td></tr>
        <tr><td>アスパラガス</td><td></td></tr>      
      </tbody>
   </table>
    </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %></h4>
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
    <h2>編集</h2>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>ユーザー名</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>メールアドレス</label>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div>
          <%= f.submit class: "btn btn-success" %>
        </div>
    <% end %>
    </div>
  </div>
</div>

ajisuke4_foodのみ/app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-7 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= current_user.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= current_user.email %></h6>
          <%= link_to 'ユーザー編集', "#" %>
        </div>
      </div>
    </div>
  </div>
</div>